---
nameOverride: ""
fullnameOverride: ""

elastic:
  enabled: true
  version: 7.10.0
  nodeSet:
    name: telemetry
    count: 9
    javaheap: "-Xms1g -Xmx1g"
    enableAntiAffinity: true #To add antiAffinity one elastic node pods
    resources:
      requests:
        memory: 2Gi
        cpu: 0.5
      limits:
        memory: 2.1Gi
        cpu: 2
    volumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
    config:
    quorum:
      enabled: true #Should be true if node count < 3
      javaheap: "-Xms1g -Xmx1g"
      resources:
        requests:
          memory: 1Gi
          cpu: 0.25
        limits:
          memory: 2Gi
          cpu: 0.5

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - host: elastic.example.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
